---
- name: Install Apache HTTPD
  hosts: all
  become: yes
  tasks:
    - name: Install httpd
      apt:
        name: httpd
        state: present

    - name: Start and enable httpd
      systemd:
        name: httpd
        state: started
        enabled: yes
