---
- name: Deploy NGINX Web Server
  hosts: all
  become: true  # Run tasks with sudo

  tasks:
    - name: Stop Apache service if running
      service:
        name: apache2
        state: stopped
      ignore_errors: yes 
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create index.html
      copy:
        content: "{{ index_content }}"
        dest: /var/www/html/index.html

    - name: Start NGINX service
      service:
        name: nginx
        state: started
        enabled: yes


