---
- name: Deploy NGINX Web Server
  hosts: all
  become: true  # Run tasks with sudo

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create index.html
      copy:
        content: "<html><body><h1>Hello from Ansible Tower!</h1></body></html>"
        dest: /var/www/html/index.html

    - name: Start NGINX service
      service:
        name: nginx
        state: started
        enabled: yes
